
import React from 'react';
import Head from 'next/head'
import {Box} from "@chakra-ui/react"

const PageRoot: React.FC = ({ children }) => {
  return (
    <Box w="100vw" h="100vh">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </Box>
  )
}

export default PageRoot
