import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Text, Box} from "@chakra-ui/react"

const Home: NextPage = () => {
  return (
    <Box d={"flex"} justifyContent="center" alignItems="center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box >
        <Text fontSize="6xl" color="brand.500">
          Stayr <Text as="a" color="blue.400" href="https://nextjs.org">Next.js</Text> template
        </Text>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </Box>
    </Box>
  )
}

export default Home
